Repository Haenaet/presenter-flutter, pull requests merged in 2023-07, with the labels that each got.

#11 Feat/seryeong #7
  lib/main.dart
  lib/screens/memberlist.dart
Labels: :blush:seryeong

#12 Feat/yujin 8
  lib/configs/palette.dart
  lib/screens/team_screen.dart
Labels: :blush:yujin

#13 Feat/mirae 6
  lib/widgets/teamintro_bottom.dart
Labels: :blush:mirae

#16 refactor: #14 memberlist, teamintro_bottom을 팀스크린에 연결
  lib/main.dart
  lib/screens/memberlist.dart
  lib/screens/team_screen.dart
Labels: :blush:seryeong

#22 add: #10 프로필 사진 꾸미기
  assets/images/나는포기하지않아.png
  assets/images/내가만든쿠키.png
  assets/images/대표캐릭터.png
  assets/images/빵찾아삼만리.png
  assets/images/커피는내친구.png
  lib/widgets/devjeans_image.dart
  lib/widgets/devjeans_picker.dart
Labels: :blush:yujin

#23 Test/drive 3
  .gitignore
  analysis_options.yaml
  android/app/src/main/AndroidManifest.xml
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/Runner/Info.plist
  lib/main.dart
  lib/models/member.dart
  lib/screens/member_create.dart
  lib/screens/member_detail_card_page.dart
  lib/screens/memberlist.dart
  lib/widgets/member_create_widget.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcworkspace/contents.xcworkspacedata
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: :blush:yujin

#24 Test/drive 1
  .gitignore
  analysis_options.yaml
  android/app/src/main/AndroidManifest.xml
  android/presenter_android.iml
  assets/fonts/Pretendard-Black.otf
  assets/fonts/Pretendard-Bold.otf
  assets/fonts/Pretendard-ExtraLight.otf
  assets/fonts/Pretendard-Light.otf
  assets/fonts/Pretendard-Medium.otf
  assets/fonts/Pretendard-Regular.otf
  assets/fonts/Pretendard-Thin.otf
  assets/images/나는포기하지않아.png
  assets/images/내가만든쿠키.png
  assets/images/대표캐릭터.png
  assets/images/빵찾아삼만리.png
  assets/images/초밥킬러.png
  assets/images/커피는내친구.png
  assets/images/콜라는제로레몬이최고야.png
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/Runner/Info.plist
  lib/configs/palette.dart
  lib/main.dart
  lib/models/member.dart
  lib/providers/member_provider.dart
  lib/screens/edit_member_screen.dart
  lib/screens/member_create.dart
  lib/screens/member_detail_card_page.dart
  lib/screens/memberlist.dart
  lib/screens/team_screen.dart
  lib/widgets/devjeans_image.dart
  lib/widgets/devjeans_picker.dart
  lib/widgets/member_create_widget.dart
  lib/widgets/teamintro_bottom.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcworkspace/contents.xcworkspacedata
  presenter.iml
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: :blush:yujin
